export const originalSha256 = "6b991b530a6c9ab038c762f56a22328d53b8615da1e59f7eace6e3e64139f815";

const identity = `Use case: identity-preserve. Asset type: production 2D Windows desktop-pet animation sprite sheet.
Input image 1 is the ORIGINAL character drawing, the only identity and costume reference. Draw exactly this same girl, Feibi Jiubi: extremely large rounded head, pale golden long hair with blunt bangs and the same side tuft, HUGE white broad-brimmed hat with black outline and blue-and-charcoal band, small blue cross-shaped hair clip, large glossy PURPLE eyes with the original dark pupils and white highlights, pink cheeks, white-and-black uniform with blue necktie and matching blue details, black gloves, and TWO small striped-sock feet with dark rounded shoes. Preserve the original outfit and accessories. Purple eyes are solid colored artwork, never transparent holes or white-only eyes. Closed eyes are clear dark curved eyelids.
STYLE: faithfully retain the source's bold thick black contour, clean rounded cartoon shapes, pale gold/white/black/blue palette and simple soft shading. Do not convert this drawing into thin anime line art, realistic painting, 3D, pixel art, a different mascot or the gray-haired red-costumed character. Her personality is bright, energetic, inquisitive and endearingly determined. Exaggerated foot push-offs, planted-foot braking, springy rebounds and delayed hat/hair motion distinguish her animation; do not express energy by merely skipping intermediate poses or speeding up an ordinary idle.

OUTPUT CONTRACT:
- Exactly one 2048 x 2048 PNG sheet, four columns by four rows, 16 equal 512 x 512 cells. Frame indices below are ZERO-BASED 0 through 15, in reading order left to right then top to bottom.
- One complete character per cell, fixed camera and character scale throughout. These are consecutive animation in-betweens, NOT a collage of unrelated poses. Do not draw grid lines, captions, frame numbers or borders.
- Pure flat chroma-magenta #FF00FF background in all cells; no gradients, shadows, texture or pale halo. The character's white hat and white uniform remain opaque white. Purple irises remain purple, never magenta.
- Complete silhouette normally occupies about 62-65 percent of cell height and at most 74 percent of cell width. Allow at least 16 percent clear magenta above the highest HAT point and at least 14 percent below the lowest shoe. Keep the ENTIRE broad brim, hair, gloves and both shoes inside each cell, even at the largest action extreme. Never crop the hat to make the figure larger.
- Keep a fixed invisible ground baseline near 82 percent of cell height for grounded actions, body around the cell center, with no overall screen travel. The program supplies translation, physics and any real Windows icon. No drawn ground, window, icon, food, cursor, hand, scenery, particles, motion lines or detached decorative marks.
- Keep both little feet recognizable and the complete hat attached in EVERY frame. During curled/side poses shoes can be tucked but remain visible. Hair, hat and clothing form one connected silhouette; hat never flies off. The tiny torso remains connected directly under the head with no elongated neck or stretched skin.
- Adjacent poses change incrementally: normal body/hat rotation changes at most 5 degrees per frame, head scale at most 3 percent, silhouette height at most 4 percent. Only the specifically mapped full-body roll can rotate farther. Express bold action cumulatively across many frames, with hat and hair lagging 1-2 frames behind the body. Never teleport, recenter each pose independently, flip facing midway or alternate standing and lying poses.
- No text, watermark, extra characters, extra limbs, giant realistic mouth, black mouth void, protruding muzzle, teeth/fangs, saliva, tears, horror, exposed underwear or exposed belly. Only intentional mouth openings have a warm coral-red interior and a small rounded pink tongue.
`;

const motions = {
  idle: `ANIMATION: a seamless grounded standing-idle loop. Face mostly front as in the original. Keep both shoes planted and head/body position steady. Frames 0-3 alert content stance, tiny breath; 4-6 one soft blink, eyebrows dip cheerfully; 7-9 eyes reopen and cheeks lift into a little smile; 10-12 one very small knee/body spring of 2 percent with hat brim lagging a beat; 13-15 settle exactly into frame 0. The broad hat should bend by a tiny amount without changing shape. No wandering glance at a cursor, hopping or large body sway. Frame 15 and 0 must be near-identical.`,

  run: `ANIMATION: seamless energetic RIGHT-facing run-in-place, two readable footstep cycles. She actively PUSHES off the invisible floor and bounds with springy tiny steps. Frames 0-1 right shoe plants with a compressed knee/body and forward intent; 2-3 right-foot push-off, left knee reaches, hat and hair lag LEFT; 4-5 compact airborne stretch with BOTH shoes visible; 6-7 left shoe lands and weight compresses with brim overshoot; 8-9 left-foot push-off; 10-11 opposite airborne passing phase; 12-13 right shoe reaches the floor; 14-15 landing compresses into frame 0. Keep the face cheerfully determined and the nose short. Translate neither body nor floor across cells. The hat brim and long hair have a clear delayed wave; the legs drive the action. Frame 15 returns smoothly to 0.`,

  walk: `ANIMATION: seamless cheerful RIGHT-facing everyday walk, clearly gentler than running. Two small deliberate planted-foot steps with a spring in the knees. Frames 0-2 right shoe forward contact and soft weight transfer; 3-5 left shoe passes while shoulders rise slightly; 6-7 left shoe touches with a little heel-settle; 8-10 weight transfers to left; 11-13 right shoe passes; 14-15 right heel returns to the starting contact. Both shoes stay visible, never slide backward while planted. Hat brim and hair sway one beat later than the footfall. Bright small smile, hands swing compactly. No airborne running leap. Adjacent frames and frame 15-to-0 join smoothly.`,

  toss: `ANIMATION: upward-toss reaction. The runtime uses ONLY FRAMES 0-7 for the rising reaction, so the clear upward inertia MUST occur in that first half. The program moves the whole character along the throw arc; keep the figure centered in each cell. Frame 0 upright just leaving support; 1 shoes lift and body compresses 3 percent; 2-3 compact whole-body upward stretch, shoes dangle while hat brim, hair and sleeves lag DOWN; 4-5 feet kick once, eyes widen with a warm surprised bean mouth, hat remains attached; 6-7 rounded light weightless pose with the original short neck and both shoes visible. Frames 8-15 continue that same airborne family with one subtle buoyant rebound and gentle delayed hat/hair flutter, ready to blend into fall. No ground contact after frame 0, no landing, no changing to horizontal, no body elongation, no stretched bare neck.`,

  fall: `ANIMATION: seamless airborne FALL loop. The program translates her downward, so no downward travel within the cells. Frames 0-3 compact upright airborne pose with feet pointing down; 4-6 hair ends, sleeve edges and broad hat brim float gently UP from descent; 7-9 knees tuck slightly and cheeks puff in determined surprise; 10-12 shoes reach downward again as fabric settles one beat late; 13-15 return continuously to frame 0. Keep torso short, face visible and hat firmly worn. One small warm open mouth, never panic or pain. Both shoes dangle separately; never an impact, floor, lying pose or superlong body.`,

  land: `ANIMATION: ONE continuous grounded two-foot landing compression, rebound and settle. Front-facing with both shoes SIDE BY SIDE on one FIXED baseline in EVERY frame. Start at first floor contact, never show a falling or airborne pose. The feet stay at the same X/Y coordinates and knees bend gradually; she NEVER sits, lies down or flattens her face against the floor. Keep the big rounded head at the SAME scale, just lower it with the bending knees. The torso, hat and head remain connected in an upright squat.
EXACT total character height relative to frame 0, in reading order: 0=100%, 1=97%, 2=94%, 3=90%, 4=87%, 5=86%, 6=88%, 7=92%, 8=96%, 9=100%, 10=103%, 11=102%, 12=100%, 13=99%, 14=100%, 15=100%. Each successive cell changes height at most 4%; row boundaries are NORMAL in-betweens. Frame 7 to 8 is just a four-percent rise, not a cut to another pose. Frames 4-6 are the same upright knee-squat family, never a pancake. Keep both shoe tips fully visible at the ground. Gloved hands move compactly near her sides; delighted small smile, eyes squeeze softly through deepest squat and reopen gradually through rebound. The broad brim and golden hair follow the knee motion one frame late with a tiny elastic flex. Her energetic resilience is clear in the planted-shoe push and overshoot. End in neutral standing ready for idle. No independent face squashing, lying/sitting intercuts, bent-over face touching feet, dust, stars or impact marks.`,

  curious: `ANIMATION: ONE seamless curious RIGHT head-tilt and return, with all 16 frames used for its in-betweens. Both shoes remain planted. Keep the same front-facing face, same body position, head scale and body height in every cell. Gloves gently rest against the blue tie throughout. Purple eyes stay open and bright with one tiny rounded inquisitive mouth.
EXACT clockwise head-and-attached-hat rotation by frame: 0=0deg, 1=1deg, 2=3deg, 3=6deg, 4=9deg, 5=12deg, 6=14deg, 7=15deg, 8=14deg, 9=12deg, 10=9deg, 11=6deg, 12=3deg, 13=1deg, 14=0deg, 15=0deg. Tilt only clockwise toward her RIGHT then return along the SAME arc. NEVER tilt left of neutral, reverse facing, or reset the pose when starting a new sheet row. Frame 7 to 8 must be almost the SAME pose, NOT opposite tilts. Frame 11 to 12 differs only 3 degrees. Frame 15 joins frame 0 without a pop. The cute expressiveness comes from wide curious purple eyes and the rounded cumulative 15-degree head tilt, not a large body lean. Hair and brim flex very subtly with a one-frame delay; do not add a second motion. No magnifying glass, punctuation, cursor, added ears or object.`,

  sleep: `ANIMATION: 16 consecutive cels: a smooth lay-down in 0-7, then a stable side-lying breathing loop in 8-15. Close both eyes with cute curved lids in EVERY frame. The same short body, round head, broad hat and hair must rotate TOGETHER as one recognizable connected little character, not change into a different seated drawing.
EXACT clockwise whole-character angles: frame0=0deg upright; frame1=12deg; frame2=26deg; frame3=40deg; frame4=54deg; frame5=67deg; frame6=79deg; frame7=90deg completely side-lying. This slow planned lay-down specifically permits the listed 12-14deg steps instead of the usual small head-tilt limit. Draw every in-between. Frame3 to4 changes by only14deg; NEVER jump from standing to sitting or from sitting to flat. Both shoe tips remain visible and tuck only slightly, no wide kick. A tiny glove supports the head side as she settles. Keep the head and hat at identical scale; each new pose follows from rotating and lowering the previous pose, without teleporting or resizing. Use a single invisible lower contact baseline, allowing the attached silhouette to get gradually wider/lower as it reclines.
Frames8,9,10,11,12,13,14,15 are ALL the SAME 90deg side-lying pose as7. Add one exceptionally small 1% breathing expansion over8-11 and contraction over12-15; no big motion or changes of orientation. Frame15 matches8. Runtime reverses0-7 for waking, so that first half must remain an uninterrupted physical arc. Entire hat brim, hair and both shoes fit well inside each cell, hat stays firmly worn. No sitting intercut, face-down collapse, pillow, blanket, sleep letters, bubbles, particles or costume removal.`,

  hungry: `ANIMATION: exactly SIXTEEN consecutive hungry animation cels in exactly FOUR rows and FOUR columns. There must be precisely FOUR figures in EVERY row, not five. One figure centered at the center of each equal512px cell; no decorative or extra pose between cells. Fixed front view and identical head size, total silhouette width and foot position throughout.
CRITICAL FRAMING: draw each entire character ONLY 300 pixels tall and no more than300 pixels wide inside its512x512cell. The WHOLE image is2048x2048, not a cropped preview. In EVERY cell the top of her hat is at localy100 and the soles at localy400. Leave112pixels of unbroken magenta BELOW the shoes, including below ALL FOUR characters in the LAST ROW. All bottom-row shoes end no lower than imagey1936, leaving the last112image rows completely magenta. The side margins are at least100pixels percell. Characters must look deliberately SMALL with generous empty magenta gutters; do not enlarge them to fill cells. Keeping this safe padding and ALL shoes complete has priority over maximizing image detail.
One glove rests on the clothed tummy, the other makes one small hopeful reaching gesture; a cute little hungry pout with wide purple eyes. Frame0 neutral pout, reaching hand at tummy; 1 elbow bends; 2 hand raises2%; 3 hand raises4%; 4 hand raises6%; 5 hand reaches8%; 6 reaches9%; 7 reaches10%; 8 same maximum pose; 9 returns9%; 10 returns7%; 11 returns5%; 12 returns3%; 13 returns1%; 14 hand back at tummy; 15 same as0. Knees make ONE subtle4% eager dip through4-7 and spring back gently through8-12. Shoes stay side by side, attached to the same ground baseline. Hat brim and hair bounce one frame after the knee motion but remain the same shape and scale. Do not reset the action at row boundaries. Greedy anticipation is endearing and hopeful, never sick or tearful. No extra person, food, icon, bowl, hunger bar, exposed belly, particles or text.`,

  climb: `ANIMATION: seamless energetic RIGHT-facing climb in place. An invisible vertical window edge lies near 70 percent cell width. The program moves her upward and mirrors when needed. Keep hand/shoe contacts along that SAME empty line. Frames 0-2 right glove reaches higher while left shoe braces; 3-5 knees and braced shoe actively PUSH as opposite glove pulls, hair and brim lag down; 6-7 compact high-phase gather; 8-10 switch hands and shoes smoothly; 11-13 second push-and-pull; 14-15 return to frame 0. Two gloves and two small shoes remain clearly connected and visible, no long limbs. Determined bright expression with a tiny effort mouth. No window, edge, ladder, handhold, rope or actual overall ascent drawn.`,

  drag: `ANIMATION: seamless lifted-and-dragged loop. An invisible hold above the hat moves the character in code; draw NO hand, string or cursor. Keep a centered upright dangling pose family in all 16 frames. The hat remains firmly worn and is never pinched or detached. Frames 0-3 two little feet dangle, compact mild surprise; 4-6 one shoe kicks gently as body sways 4 degrees LEFT, hair/sleeves trail; 7-9 pass through center with a soft whole-body rebound of at most 4 percent; 10-12 opposite shoe kicks and sway reaches 4 degrees RIGHT; 13-15 settle smoothly into frame 0. The broad brim bobs one beat late; arms are short and attached. No ground, horizontal lying pose, elongated neck or changing head scale.`,

  jump: `ANIMATION: one energetic upright jump reaction, using SIXTEEN closely spaced in-betweens from the SAME pose family. Fixed slight three-quarter RIGHT-facing orientation in ALL frames, no facing changes. The program handles the flight arc, so character center stays fixed. Keep identical head/hat scale and overall height varying at most5%; body stays short and upright, gloves compact at the sides and BOTH striped shoes always under the torso.
Frames0-2 shoes push downward decisively with a little knee spring and a determined happy face; 3-5 legs extend only5%, brim and golden hair trail down; 6-8 gradually bend knees and pull both shoes up only5% below the torso, with the SAME upright body angle; 9-11 gently straighten knees again to prepare feet for descent; 12-15 remain upright airborne with shoes pointing down, hair ends and hat brim lifting a little from falling air. The last frame is STILL AIRBORNE, not a new standing front-view drawing. The separate land animation supplies all impact and standing recovery. No sitting pose, curled ball, holding knees, folding feet in front of chest, reclining or abruptly switching pose at frame7 or14. Preserve two separate visible shoes below the body throughout. At every sheet-row boundary continue the same motion by a tiny amount, never start a new pose. Warm excited smile, delayed hair/brim flex, no panic, ground, effects or detached hat.`,

  slide: `ANIMATION: seamless RIGHT-facing slide DOWN an invisible vertical window edge. The body stays LEFT of a fixed contact line near 70 percent of each cell width. Both gloves always contact that SAME line within 2 percent across the sheet, while both tiny shoes alternately brace lower against it. Frames 0-3 hands hold and knees extend a little; 4-6 one shoe reaches lower, the other remains visible; 7-9 a small friction squash and cheek puff; 10-12 switch shoes with a tiny elastic slip; 13-15 brim, hair and tie complete upward lag and return to frame 0. Runtime supplies descent; never move overall down within cells. Keep short limbs, attached hat and clear purple eyes. No drawn window, wall, rope or visible contact guide.`,

  roll: `ANIMATION: one full playful hungry roll in place, then spring back up. Rotate the WHOLE connected clothed character/hat together; never separately rotate head or expose underwear. Frame 0 upright pout; 1 knee crouch; 2 tilt RIGHT 15 degrees; 3 tilt 40 degrees; 4 compact rotation 70 degrees; 5 105 degrees; 6 140 degrees; 7 175 degrees; 8 210 degrees; 9 245 degrees; 10 280 degrees; 11 315 degrees; 12 return to a low upright 350-degree crouch; 13 both shoes firmly push into a little rebound; 14 hat/hair overshoot; 15 stable upright. Rotation progresses in ONE direction without missing steps. Broad hat stays firmly worn; hair wraps into the connected silhouette. Both dark shoe tips are visible even tucked. Keep the full rotating silhouette inside the same padded box; no sliding across cells, stars, spiral eyes or detached hat.`,

  lick: `ANIMATION: one continuous LEFT-facing icon taste-test. The REAL icon is supplied separately LEFT of the character; do NOT draw any target. She stands on the icon's RIGHT, remains upright on both planted shoes, and leans LEFT without changing facing. Anchor face center and foot baseline. The contact for the tongue tip is near 34 percent cell width and 48 percent cell height; frames 7-9 must maintain the SAME contact within 2 percent. Tongue is short, broad, strawberry-pink with a blunt rounded tip, never long/thin or forked. Frame 0 attentive; 1 hands lift; 2 knees dip only 4 percent; 3 lean LEFT 4 degrees; 4 lean 8 degrees and warm small mouth opens; 5 tongue peeks; 6 extends halfway; 7 reaches fixed contact; 8 near-identical contact with tiny cheek puff; 9 still contact, start release; 10 tongue retracts halfway; 11 tip almost hidden; 12 tongue gone and lips close; 13 pleased cheek puff; 14 small upright rebound; 15 neutral delighted settle. Hat and golden hair lag gently RIGHT but NEVER obscure mouth/eyes. No sitting, floor pancake, saliva, giant tongue, viewer-facing licking or icon drawn.`,

  chomp: `ANIMATION: one continuous LEFT-facing inhale-and-eat action, with a VERY LARGE visible open mouth. The real deleted-icon ghost is supplied by code on the LEFT. Character stands on the icon's RIGHT and opens her mouth LEFT, not front or right. Keep both shoes firmly on a single contact point and the face following one shallow smooth arc. Do not lift or punch an icon, and draw no icon/food/effects.
MOUTH: a large soft vertical rounded bean opening INSIDE the left side of the existing round face; maximum 52-58 percent of FACE height (excluding hat/hair), 36-42 percent of face width. Thick soft outline with warm coral-red inner mouth and small lighter pink tongue at bottom, never a black void or projecting tube. Purple eyes remain visible above and behind the mouth with original pupils/highlights; squint cutely but do not erase them. The mouth entry point remains steady through frames 6-10 so the real icon enters visibly.
EXACT MAP: 0 greedy notice, closed mouth; 1 small planted-foot knee compression and lifted gloves; 2 lean RIGHT 5 degrees; 3 lean RIGHT 10 degrees, mouth opens 15 percent; 4 lean RIGHT 15 degrees, mouth 28 percent; 5 lean RIGHT 20 degrees, mouth 42 percent; 6 lean RIGHT 25 degrees, mouth 54 percent; 7 lean RIGHT 29 degrees, maximum mouth 58 percent; 8 near-duplicate of 7 with same mouth and entry point, only golden hair and brim lag farther RIGHT; 9 small recoil to 25 degrees, mouth still 54 percent; 10 recoil to 20 degrees, mouth still 46 percent as icon completes entry; 11 lean 15 degrees, opening reduces to 30 percent; 12 lean 10 degrees, lips close and cheeks puff; 13 upright planted-foot compression with stuffed round cheeks; 14 gentle whole-body swallow rebound, hat lagging; 15 satisfied upright settle. Mouth closing is gradual, never instantly tiny after maximum suction. Exaggerated appetite comes from visible huge mouth, cumulative lean, strong shoe brace and delayed hat/hair flutter, not teleporting or horror. No lips projecting outside face, muzzle, snout, tube, fangs, saliva, black cavity, missing eyes or turning to front.`,

  satisfied: `ANIMATION: one complete post-meal satisfied reaction, begin and end upright with both shoes visible. Frames 0-2 cheeks inflate into happy round buns and gloves move to the fully clothed tummy; 3-5 eyes squeeze into delighted curves, a proud little smile; 6-8 knees compress into a plump happy stance, broad brim follows downward a beat late; 9-11 a spirited but small rebound through planted shoes and satisfied upward stretch of at most 7 percent; 12-14 hair/brim and cheeks wobble then calm; 15 exact neutral pleased stance. All poses remain upright and one coherent family, no sitting or lying intercuts, enormous jump, lip licking toward viewer, exposed belly, steam or sparkles.`,
};

export const actions = Object.freeze(Object.keys(motions));
export const prompts = Object.freeze(Object.fromEntries(
  Object.entries(motions).map(([action, motion]) => [action, `${identity}\n${motion}\n`]),
));
