export const originalSha256 = "6b991b530a6c9ab038c762f56a22328d53b8615da1e59f7eace6e3e64139f815";

const identity = `Use case: identity-preserve
Asset type: production Windows desktop-pet hand-drawn animation sprite sheet.
Input images: Image 1 is the user's ORIGINAL Feibi Jiubi (菲比啾比) character reference, the ONLY identity reference. Create a complete NEW sheet directly from that original; never imitate another generated sprite sheet.
Character: the exact cheerful lively cute chibi girl from the reference. Huge rounded pale-gold hair, purple eyes WITH the reference's pupils and white highlights, thick clean black outlines, blush cheeks, tiny blue-white-black coat and tie, black gloves, TWO short striped-sock legs and dark shoes. Preserve the reference's blue cross hairclip and tiny sideways hair tuft. Short connected neck and torso, no realistic anatomy. Keep original facial proportions and color palette. When worn, the hat is the exact BROAD white brim, black crown with blue band. When removed, the same round golden head has a simple smooth hair crown, no extra hairstyle, bald scalp or new ornament. Her mood is playful determination, never anger, horror or cruelty.
Composition: exactly 2048x2048 PNG, exactly FOUR rows and FOUR columns of equal invisible 512x512 cells, precisely SIXTEEN successive animation cels in row-major order, one complete character per cell. Background solid pure saturated magenta #FF00FF, including all spaces between limbs and props. NO gridlines, numbers, text or borders.
Framing: each complete figure including hat, feet, extended hands and action extrema fits in a local 350x350 box centered at x256 and y270, with all colored pixels within local x80..432 and y70..440. Leave generous magenta gutters and at least72 pixels below ALL bottom-row shoes. DO NOT enlarge characters to fill the cells. Never cut hats, shoes or hands on cell/image borders.
Animation: sixteen consecutive drawn in-betweens, no row resets, no independent poses, no sudden facing changes or camera zoom. Keep the same head size, same invisible ground baseline localy425 and same ground-contact X except deliberate leg motion. The program supplies world-space travel, windows, forces and effects. Do NOT draw windows, target objects, paper scraps, floor, impact marks, stars, wind, dust, cursors, motion lines or extra people. Use cumulative broad body poses, clearly readable anticipation, delayed hair/hat follow-through and a cute reaction. The tiny body stays clothed, complete, connected and recognizable, with TWO shoes visible even while airborne. Side actions consistently face screen LEFT: she stands to the RIGHT of an invisible window and acts toward the LEFT.
Keep clean flat cel shading, no photorealism, no 3D, no blurred interpolation, no doubled limbs, no teeth, saliva, huge mouth or grotesque facial distortion. Warm small coral bean mouth or smile only. All cells are equally detailed.
`;

const motions = {
  prank_sneak: `Hat WORN throughout. Seamless LEFT-facing tiptoe sneak-in-place. 0-3 one lifted small knee and sly bright glance LEFT;4-7 gently put that shoe down with bent knees;8-11 opposite knee tiptoe,gloves tucked beside cheeks;12-15 settle smoothly into0. Exaggerate the alternating little knees and mischievous smile, hair and broad brim lag one beat. No hand-to-mouth eating, no object.`,
  kick: `Hat WORN throughout. ONE clear LEFT-facing martial-arts side KICK with the LEFTMOST shoe, the other shoe stays planted. Frame0 ready upright;1-3 shift weight RIGHT and lean away;4-5 raise LEFT knee visibly in front;6 begin extending leg LEFT;7 almost straight;8 maximum LEFT kick contact with dark shoe toe at localx100,y350;9 same contact with tiny elastic compression;10-11 retract shoe along same path;12 knee lowers;13-14 one cute single-foot wobble;15 both shoes planted and pleased. The LEFT shoe, not hand or hair, must be leftmost at contact. Show the stripe sock on the kicking leg, keep legs short but visibly separated. Same hat/head scale throughout.`,
  punch: `Hat WORN throughout. ONE clear LEFT-facing forward PUNCH. 0 upright cheerful determination;1-3 pull leftmost glove back beside cheek, bend knees4%;4-5 torso rotates only8 degrees toward LEFT and elbow uncoils;6-7 gloved fist extends;8 maximum punch with LEFT fist at localx98,y310, elbow connected to tiny shoulder;9 tiny contact compression;10-12 retract along same arc;13-14 shake that small glove once by her side;15 upright smug little grin. Both shoes planted. The glove is clearly distinguishable from hair, arm never elongated.`,
  charge: `Hat WORN throughout. ONE LEFT-directed shoulder bump, SAME FRONT-THREE-QUARTER face orientation and SAME head/hat/body SIZE in EVERY cell. The character is exactly300px tall at neutral, head/hat same width throughout; never shrink to fit a long flying-hair silhouette. Program supplies travel, do not fly/slide across cells. Frame0 upright front-three-quarter toward LEFT, same original-like standing pose and two visible planted shoes;1-3 knees dip3% as she pulls both gloves to chest;4-5 body leans LEFT10deg with shoulder leading;6-7 lean reaches15deg while little legs push against floor;8 shoulder hits invisible edge at localx160,y300,body stays mostly upright leaning15deg,face remains same three-quarter front;9 tiny4% knee compression from hit;10 lean eases to12deg;11 to8deg;12 to4deg;13 upright0deg;14-15 standing front-three-quarter original pose with both shoes and gloves lowered, matching frame0, ready for separate butt-bump recoil. Never turn into SIDE PROFILE, never horizontal Superman flying, never rotate head separately or finish looking backward. Keep broad expressive anticipation and delayed hair/brim sweep within20px, NOT a long horizontal hair tail. All extremities stay inside350px safe box.`,
  recoil: `Hat WORN throughout. One small funny butt-bump and VERY SMOOTH stand-up, front/slight LEFT view in all frames. Big round head and broad hat remain EXACTLY the SAME scale and upright angle. Only tiny knees and hips lower/raise; both shoes always visible. Total character heights relative to frame0 MUST be: 0=100%,1=98%,2=94%,3=90%,4=86%,5=83%,6=82%,7=82%,8=83%,9=85%,10=87%,11=90%,12=93%,13=97%,14=100%,15=100%. The lowest pose is a compact little seated butt-bump with knees bent in front but never less than82% standing height. Frame8,9,10,11,12,13 are SIX successive stand-up in-betweens; NEVER suddenly reset to full upright at11. Frame10->11 changes only3% height. Gloves brace beside knees then slowly release as shoes push to stand. Show playful surprise early and tiny sheepish grin at end. Fixed shoe contact baseline, no actual screen travel. No flying/sideways/lying pose, no broad arm gesture, no extra bounce after frame14, no facial stretching.`,
  hat_open: `ONE smooth hat-removal and presentation.0 exact original hat WORN, front/slight LEFT view;1-3 both gloves rise to brim;4-6 lift same hat off head slowly, revealing complete rounded golden crown;7-9 move held hat DOWN toward front LEFT of torso;10-12 tilt hat so its dark OPEN INSIDE faces UP and slightly viewer;13-15 hold it steady at waist, brim opening centered localx220,y342, ellipse width170 height44. Hat must be upside-down container with crown BELOW the brim opening, white front brim visible. Both gloves grasp opposite edges, hat touches hands and figure. End bareheaded, exactly ONE hat held in front, never a duplicate worn hat. Preserve both shoes below it.`,
  hat_store: `Head BARE throughout, exactly ONE original hat HELD upside-down at front LEFT waist with open dark inner ellipse facing UP, crown below brim. Hat opening stays at localx220,y342 and width170 height44 through0-9; both gloves grasp its edges, TWO shoes visible below.0-3 eager look down into opening;4-7 knees flex a little and cheeks lift;8-9 hold opening steady;10-12 one glove slides across the top to gently cover it;13-15 both gloves press the brim lightly, proud tiny smile. Nothing enters in drawing: the real window card will be composited later. No worn hat, no added object, no black void on face.`,
  hat_hold: `Head BARE, exactly ONE original hat held at front waist, crown underneath and brim facing UP. Seamless small loop pretending innocence while concealing something in the hat. Both gloves stay on brim, opening centered localx220,y342;0-4 hat crown bulges only3% outward while her purple eyes glance LEFT;5-8 she presses it down gently with both gloves and blinks;9-12 crown returns while cheeks smile;13-15 returns smoothly to0. Don't put hat on head, no object inside, no covering face, both shoes visible.`,
  hat_return: `Head BARE throughout; exactly ONE original hat held upside-down in front at waist, opening centered localx220,y342.0-3 hands lift gently from covering brim to hold both edges,eyes peek down;4-7 tip open hat toward LEFT by a cumulative10deg as if letting an unseen small window card slide out;8-10 hold open and beam proudly;11-13 return tilt to upright opening;14-15 steady open-hat pose matching end of hat_open. Draw no card or object. Hat stays in hands, no worn hat. Both feet planted.`,
  gloat: `Hat WORN throughout. One cute smug celebration after harmless mischief.0-3 small front-facing grin and gloves on hips;4-7 knees spring4% upward and shoulders puff proudly;8-10 one glove points LEFT with playful wink;11-13 hand returns to hip and hair settles;14-15 exact upright neutral. Keep exuberant but not laughing wildly, no food/tummy gesture. Both shoes planted.`,
  hat_throw: `ONE precise hat toss transition in 16 successive cels. Fixed FRONT body view, same face/feet position in ALL16. The throw is ONLY toward SCREEN RIGHT. The arms must NEVER point to SCREEN LEFT in ANY cell. Frame0 hat WORN;1-2 both gloves grip brim;3-4 lift it slightly above crown;5 lift both hands to RIGHT above shoulder with held hat;6 hands and hat at localx330,y180;7 hands extend 3px farther UP RIGHT at localx335,y175 with hat STILL TOUCHING fingers. Frame8 MUST COPY frame7's complete body/head/arm/hand pose and location, ONLY remove the hat and open fingertips: both hands STILL at localx335,y175 SCREEN RIGHT. Frames9,10,11 follow through along the SAME RIGHT-side arc at (337,183),(332,198),(322,220);12 hands lower RIGHT at(310,248);13 at(294,275);14 hands by right side(282,300);15 bareheaded ready stance, arms relaxed. Hat is ABSENT in8-15 because runtime draws independent hat. No flying hat, trail, second hat or alternate throw to LEFT. The row2-to-row3 boundary 7->8 is almost IDENTICAL apart from removed hat. Keep original compact short arms, rounded golden crown fully revealed, purple eyes and both shoes visible. Hat and figure remain fully inside safe cell bounds.`,
  bare_idle: `NO HAT anywhere in ANY cell. Original identity, same rounded complete golden hair crown. Seamless confident lively idle.0-3 feet planted,gloves loosely at sides,bright purple eyes;4-6 small blink;7-10 tiny eager knee spring3%;11-15 settle to0. No glove on head, no object, no new hairstyle or ears.`,
  bare_run: `NO HAT anywhere in ANY cell. Seamless energetic LEFT-facing run-in-place with two tiny bounding strides.0-3 left shoe drives backward while other knee reaches LEFT, torso leans LEFT10deg;4-7 feet exchange in compact airborne phase;8-11 opposite foot landing and push;12-15 return to0. Runtime supplies travel. Golden hair clearly streams RIGHT a beat late. Original big head remains upright connected to tiny fully clothed body, TWO separate shoes always visible.`,
  bare_kick: `NO HAT anywhere in ANY cell. ONE exuberant LEFT-facing jumping side kick; runtime supplies leap arc.0-2 compact standing windup;3-5 left knee rises while planted foot pushes;6-7 knee unfolds LEFT and opposite shoe tucks below torso;8 maximum LEFT kick, dark shoe toe at localx98,y330, original purple eyes determined and little smile;9 tiny hit compression;10-11 kick retracts smoothly;12-14 both shoes gather below body, torso tilts RIGHT only15deg in funny recoil;15 compact airborne recovery. Keep head scale fixed, no whole body spins or abrupt standing reset. TWO shoes and striped socks visible, no impact effect or target.`,
  bare_tear: `NO HAT anywhere. ONE readable two-handed imaginary-window tearing action, body three-quarter LEFT, feet planted.0-2 both empty black gloves reach to screen LEFT in front of torso;3 both gloves grip the same invisible vertical edge at localx125, with upper glove y270 and lower glove y350;4-6 cheeks puff and knees dip while hands begin separating vertically along that LEFT edge;7 separation grows;8 clear tearing strain with upper glove localx112,y235 and lower glove localx115,y378;9-10 arms hold maximum split;11-12 gloves relax apart, eye smile;13-14 shake lower glove once as if an unseen scrap stuck;15 lower hands into bare idle. The hands must stay on LEFT SIDE of face/body, never symmetric spread to both sides like a dance. Draw NO paper/window/scraps, code supplies them. Short anatomically connected arms, do not stretch head or neck.`,
  bare_recover: `NO HAT anywhere. One compact airborne-to-landing recovery after big prank.0 upright airborne with knees a little tucked,body tilted RIGHT10deg;1-3 shoes extend down and angle returns0;4-7 both shoes land on same fixed baseline, knees gradually bend into squat,head retains scale;8 deepest squat at86% standingheight;9-12 both planted shoes push upright with lively rebound;13-15 settle original bareheaded upright pose. Golden hair follows the knee compression a beat late, no sitting or lying pose, no extra object.`,
  bare_drag: `NO HAT anywhere. Seamless upright lifted/dangling reaction. Body stays centered,gloves out a little,two shoes dangle separately.0-4 sway only4deg LEFT as one shoe kicks;5-8 pass through middle;9-12 sway4deg RIGHT opposite shoe;13-15 return0. Cute tiny surprised coral mouth and purple eyes. Invisible pointer supplies lift but draw NO cursor, hand or string. Keep rounded complete golden crown, no long neck.`,
  bare_fall: `NO HAT anywhere. Seamless upright falling loop, program supplies downward world travel. Both shoes point down separated, arms lightly out, golden hair ends float UP a little.0-4 compact buoyant pose;5-8 knees gather only4%;9-12 feet extend again;13-15 return0. Same head size and golden crown, warm surprised determined face, no ground or landing pose.`,
  hat_pickup: `ONE smooth pickup of her original hat from the ground at screen RIGHT. Head BARE in ALL16frames.0 upright bareheaded looks RIGHT-down with NO hat drawn;1-3 bends knees and reaches right glove DOWN RIGHT,hat remains absent because program draws ground prop;4 fingertips grip brim and exact original hat first appears connected to glove at localx330,y400;5-8 slowly lift hat toward waist while knees straighten;9-12 other glove joins brim and rotate hat upside-down with opening UP;13-15 steady front-held openhat position, opening localx220,y342, matching hat_open end. Exactly ONE held hat from4 onward, never duplicate worn or detached ground hat. Both shoes visible; keep whole heldhat inside safe cell bounds.`,
  hat_wear: `ONE smooth held-hat-to-worn transition.0-2 BARE head and exactly ONE original hat held in front,open side UP at localx220,y342;3-5 lift it slightly and smoothly turn opening DOWN;6-9 both gloves raise hat in front of face to above golden crown without hiding BOTH eyes at once;10-12 lower brim gently onto head;13-14 gloves pat both sides of brim;15 neutral original hat WORN, gloves at sides. Head size and golden hair unchanged, exactly ONE hat throughout. Keep whole broad hat and two shoes inside each cell. No suddenly appearing duplicate hat or blink cut.`,
  hat_prop: `PROP ONLY, no girl, no face, no limbs, no hair. Produce sixteen clean drawings of ONLY the EXACT original broad white-brimmed black-and-blue-band hat, isolated on magenta. Same size in all512cells, width300, height130, centered.0-3 top/front three-quarter view as worn with small 0,5,10,15degree clockwise tilts;4-7 continue20,25,30,35degrees;8-11 hat lying on ground slight tilt0,5,0,-5degrees;12-15 upside-down open container showing dark inner ellipse, crown BELOW opening, white front brim, four near-identical openhat views. No decorative marks. Hat must be one connected complete silhouette, not cut at edges.`,
};

export const actions = Object.freeze(Object.keys(motions));
export const prompts = Object.freeze(Object.fromEntries(Object.entries(motions).map(([key, value]) => [key, `${identity}\nANIMATION: ${value}\n`])));
